Vagrant.configure("2") do |config|
    config.vm.define "kali" do |kali|
      kali.vm.box = "kalilinux/rolling"
      kali.vm.network "public_network", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC"
      kali.vm.provider "virtualbox" do |vb|
        vb.memory = "4096"
        vb.cpus = 4
      end
    end
  end