Vagrant.configure("2") do |config|
    config.ssh.username = 'vagrant'
    config.ssh.password = 'vagrant'
    
    config.vm.define "kali" do |kali|
      kali.vm.box = "kalilinux/rolling"
      kali.vm.network "public_network", bridge: "Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC"
      kali.vm.provider "virtualbox" do |vb|
        vb.memory = 4096
        vb.cpus = 4
      end
    end
  
    config.vm.define "ub1404" do |ub1404|
      ub1404.vm.box = "rapid7/metasploitable3-ub1404"
      ub1404.vm.hostname = "metasploitable3-ub1404"
      ub1404.vm.network "private_network", ip: '172.28.128.3'
      ub1404.vm.provider "virtualbox" do |v|
        v.name = "Metasploitable3-ub1404"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end
  